### ISSUE TITLE
Anomaly Detection Model

### ISSUE THREAD

**Issue by hkayann** [ARM-software/ML-zoo#14]
In your paper titled "MICRONETS: NEURAL NETWORK ARCHITECTURES FOR DEPLOYING TINYML APPLICATIONS ON COMMODITY MICROCONTROLLERS" you also mention an anomaly detection model. However I am not able to spot it. Is it included in this repo?

**Comment by robell** [comment]
hi @hkayann - now available here: https://github.com/ARM-software/ML-zoo/tree/master/models/anomaly_detection
