### ISSUE TITLE
Cannot load input file 0.pny, complained "Failed to interpret file '0.npy' as a pickle" or "invalid load key, 'v'."

### ISSUE THREAD

**Issue by johnpzh** [ARM-software/ML-zoo#19]
Hi there,

I have been working to test the model **CNN Large INT8** model of **Keyword Spotting** in a Tensorflow Lite for Micro (TFLM) program. I got some issues when loading the input file.

When I tried to use `numpy` to load `0.npy`, I got some errors as follows.
```
>>> import numpy as np
>>> np.load('0.npy')

Traceback (most recent call last):
  File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/envs/ml-zoo/lib/python3.6/site-packages/numpy/lib/npyio.py", line 426, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/envs/ml-zoo/lib/python3.6/site-packages/numpy/lib/npyio.py", line 429, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '0.npy' as a pickle

>>> np.load('0.npy', allow_pickle=True)

Traceback (most recent call last):
  File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/envs/ml-zoo/lib/python3.6/site-packages/numpy/lib/npyio.py", line 426, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/envs/ml-zoo/lib/python3.6/site-packages/numpy/lib/npyio.py", line 429, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '0.npy' as a pickle
```

I'm using `Python 3.6.13` and `numpy 1.12.1`. 

I did some research and checked `0.npy`'s version using command `xxd`:

```
$ xxd 0.npy
00000000: 7665 7273 696f 6e20 6874 7470 733a 2f2f  version https://
00000010: 6769 742d 6c66 732e 6769 7468 7562 2e63  git-lfs.github.c
00000020: 6f6d 2f73 7065 632f 7631 0a6f 6964 2073  om/spec/v1.oid s
00000030: 6861 3235 363a 3661 6239 3364 3438 3263  ha256:6ab93d482c
00000040: 3035 6365 3533 6664 3436 3766 3431 3964  05ce53fd467f419d
00000050: 3637 3635 3333 3531 6330 6236 6136 6434  67653351c0b6a6d4
00000060: 3436 3634 3834 6139 3034 3138 3363 3936  466484a904183c96
00000070: 3764 3736 3135 0a73 697a 6520 3230 3838  7d7615.size 2088
00000080: 0a
```

It seems to be `v1` npy file. I'm not sure if this was the problem.

Would you mind give me some advice about how to read the input file? Also by any chance could you tell me how to load this `npy` file into the TFLM project which is using C/C++? 

Thank you so much!

**Comment by tom-arm** [comment]
Hi @johnpzh,

It appears you have not pulled the Numpy binary files, but rather the Git LFS pointers to those files. To fix this issue I would recommend the following:
- Install Git LFS: https://git-lfs.github.com
- The run the following commands in the repository: `git lfs install` & `git pull`.

This should download the binary files.

I hope this helps!

**Comment by johnpzh** [comment]
Hi Tom,

Thanks for your reply! I did what you told me and got the real `0.npy` file successfully!

I was wondering how I could include those inputs in the C/C++ code. Would you mind give me some advice? I am a newbie about Tensorflow Lite for MCU and MCU programming. My apology if the question looks stupid.

Thank you so much!

**Comment by henriwoodcock** [comment]
@johnpzh your best bet would be to write the array to a file and then make a header file out of it and include that in your project. You can do this in NumPy

```python
array = (your np.array)
filename = "numpy_output.h"
array.astype('int8').tofile(filename)
```

You would then need to do some edits by hand to get it into C array format, but most of the work will be done.

**Comment by johnpzh** [comment]
Thank you so much! That helps a lot!
