### ISSUE TITLE
Cannot download SSD MobileNet v1 FP32

### ISSUE THREAD

**Issue by AIWintermuteAI** [ARM-software/ML-zoo#21]
Perhaps I'm missing something obvious, but the repository actually doesn't contain model files.
https://github.com/ARM-software/ML-zoo/blob/master/models/object_detection/ssd_mobilenet_v1/tflite_fp32/ssd_mobilenet_v1.tflite

This is just plan text file with the following content 
version https://git-lfs.github.com/spec/v1
oid sha256:d15f8495fce308b774fd25cf4584e6f682f2d9d1b7cb6aa81cea2d784874c51b
size 27286108

The size  26 MB, but even when I press on Raw it only shows the same information as above.

+ this link leads to .pb and saved model files and does not contain .tflite model
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz

I'm testing ARM NN and trying to understand the performance difference between FP32 and INT8 models. Having official models for the comparison would help greatly.

**Comment by henriwoodcock** [comment]
Hi @AIWintermuteAI, the models are currently down for some reason. However with the model you are using there you can recreate the model. Try running the following command:

```bash
cd models/object_detection/ssd_mobilenet_v1/tflite_fp32/recreate_model
./recreate_model.sh
```

**Comment by AIWintermuteAI** [comment]
Great, that will suffice for this particular model.
But I think something is wrong with repository models in general...
https://github.com/ARM-software/ML-zoo/tree/master/models/speech_recognition/wav2letter/tflite_int8
This one doesn't have a original model download/conversion materials...

**Comment by robell** [comment]
hi @AIWintermuteAI - this was due to quota issues on the Arm-software account, you should now find that the model files are populated if you clone the repo, and the models on the web interface can be downloaded again. please re-open if you have any issues.
